# Generated by Django 5.2.4 on 2025-08-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='post_image',
        ),
    ]
